# Auto generated, do not edit.

PRODUCT_COPY_FILES += \
    prebuilts/calyx/fdroid/fallback-icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/fallback-icon.png \
    prebuilts/calyx/fdroid/repo/at.bitfire.davdroid/en-US/icon_NexNou7vmaD45rbdc8kjLj0Rv7FW128Mde9OQpHFXPE=.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/at.bitfire.davdroid/en-US/icon_NexNou7vmaD45rbdc8kjLj0Rv7FW128Mde9OQpHFXPE=.png \
    prebuilts/calyx/fdroid/repo/at.bitfire.davdroid/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/at.bitfire.davdroid/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/categories.txt:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/categories.txt \
    prebuilts/calyx/fdroid/repo/com.fsck.k9/en-US/icon_-2bZW0ZnkKqPVher2SxQK8hXGGSjgaBHoa8x6vW0v8w=.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.fsck.k9/en-US/icon_-2bZW0ZnkKqPVher2SxQK8hXGGSjgaBHoa8x6vW0v8w=.png \
    prebuilts/calyx/fdroid/repo/com.fsck.k9/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/com.fsck.k9/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/icons-120/app.organicmaps.21070806.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/app.organicmaps.21070806.png \
    prebuilts/calyx/fdroid/repo/icons-120/com.artifex.mupdf.viewer.app.90.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/com.artifex.mupdf.viewer.app.90.png \
    prebuilts/calyx/fdroid/repo/icons-120/com.aurora.store.38.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/com.aurora.store.38.png \
    prebuilts/calyx/fdroid/repo/icons-120/com.duckduckgo.mobile.android.58901.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/com.duckduckgo.mobile.android.58901.png \
    prebuilts/calyx/fdroid/repo/icons-120/com.jarsilio.android.scrambledeggsif.67.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/com.jarsilio.android.scrambledeggsif.67.png \
    prebuilts/calyx/fdroid/repo/icons-120/com.yubico.yubioath.20199.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/com.yubico.yubioath.20199.png \
    prebuilts/calyx/fdroid/repo/icons-120/info.guardianproject.locationprivacy.31.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/info.guardianproject.locationprivacy.31.png \
    prebuilts/calyx/fdroid/repo/icons-120/org.briarproject.briar.android.10305.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/org.briarproject.briar.android.10305.png \
    prebuilts/calyx/fdroid/repo/icons-120/org.calyxinstitute.vpn.149.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/org.calyxinstitute.vpn.149.png \
    prebuilts/calyx/fdroid/repo/icons-120/org.dmfs.tasks.82200.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/org.dmfs.tasks.82200.png \
    prebuilts/calyx/fdroid/repo/icons-120/org.secuso.privacyfriendlyweather.14.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/org.secuso.privacyfriendlyweather.14.png \
    prebuilts/calyx/fdroid/repo/icons-120/org.sufficientlysecure.keychain.57500.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/org.sufficientlysecure.keychain.57500.png \
    prebuilts/calyx/fdroid/repo/icons-120/org.thoughtcrime.securesms.87700.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/org.thoughtcrime.securesms.87700.png \
    prebuilts/calyx/fdroid/repo/icons-120/org.torproject.torbrowser.2015808091.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/org.torproject.torbrowser.2015808091.png \
    prebuilts/calyx/fdroid/repo/icons-120/se.leap.riseupvpn.155.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-120/se.leap.riseupvpn.155.png \
    prebuilts/calyx/fdroid/repo/icons-160/app.organicmaps.21070806.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/app.organicmaps.21070806.png \
    prebuilts/calyx/fdroid/repo/icons-160/com.artifex.mupdf.viewer.app.90.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/com.artifex.mupdf.viewer.app.90.png \
    prebuilts/calyx/fdroid/repo/icons-160/com.aurora.store.38.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/com.aurora.store.38.png \
    prebuilts/calyx/fdroid/repo/icons-160/com.duckduckgo.mobile.android.58901.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/com.duckduckgo.mobile.android.58901.png \
    prebuilts/calyx/fdroid/repo/icons-160/com.jarsilio.android.scrambledeggsif.67.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/com.jarsilio.android.scrambledeggsif.67.png \
    prebuilts/calyx/fdroid/repo/icons-160/com.yubico.yubioath.20199.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/com.yubico.yubioath.20199.png \
    prebuilts/calyx/fdroid/repo/icons-160/info.guardianproject.locationprivacy.31.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/info.guardianproject.locationprivacy.31.png \
    prebuilts/calyx/fdroid/repo/icons-160/org.briarproject.briar.android.10305.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/org.briarproject.briar.android.10305.png \
    prebuilts/calyx/fdroid/repo/icons-160/org.calyxinstitute.vpn.149.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/org.calyxinstitute.vpn.149.png \
    prebuilts/calyx/fdroid/repo/icons-160/org.dmfs.tasks.82200.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/org.dmfs.tasks.82200.png \
    prebuilts/calyx/fdroid/repo/icons-160/org.secuso.privacyfriendlyweather.14.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/org.secuso.privacyfriendlyweather.14.png \
    prebuilts/calyx/fdroid/repo/icons-160/org.sufficientlysecure.keychain.57500.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/org.sufficientlysecure.keychain.57500.png \
    prebuilts/calyx/fdroid/repo/icons-160/org.thoughtcrime.securesms.87700.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/org.thoughtcrime.securesms.87700.png \
    prebuilts/calyx/fdroid/repo/icons-160/org.torproject.torbrowser.2015808091.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/org.torproject.torbrowser.2015808091.png \
    prebuilts/calyx/fdroid/repo/icons-160/se.leap.riseupvpn.155.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-160/se.leap.riseupvpn.155.png \
    prebuilts/calyx/fdroid/repo/icons-240/app.organicmaps.21070806.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/app.organicmaps.21070806.png \
    prebuilts/calyx/fdroid/repo/icons-240/com.artifex.mupdf.viewer.app.90.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/com.artifex.mupdf.viewer.app.90.png \
    prebuilts/calyx/fdroid/repo/icons-240/com.aurora.store.38.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/com.aurora.store.38.png \
    prebuilts/calyx/fdroid/repo/icons-240/com.duckduckgo.mobile.android.58901.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/com.duckduckgo.mobile.android.58901.png \
    prebuilts/calyx/fdroid/repo/icons-240/com.jarsilio.android.scrambledeggsif.67.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/com.jarsilio.android.scrambledeggsif.67.png \
    prebuilts/calyx/fdroid/repo/icons-240/com.yubico.yubioath.20199.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/com.yubico.yubioath.20199.png \
    prebuilts/calyx/fdroid/repo/icons-240/info.guardianproject.locationprivacy.31.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/info.guardianproject.locationprivacy.31.png \
    prebuilts/calyx/fdroid/repo/icons-240/org.briarproject.briar.android.10305.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/org.briarproject.briar.android.10305.png \
    prebuilts/calyx/fdroid/repo/icons-240/org.calyxinstitute.vpn.149.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/org.calyxinstitute.vpn.149.png \
    prebuilts/calyx/fdroid/repo/icons-240/org.dmfs.tasks.82200.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/org.dmfs.tasks.82200.png \
    prebuilts/calyx/fdroid/repo/icons-240/org.secuso.privacyfriendlyweather.14.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/org.secuso.privacyfriendlyweather.14.png \
    prebuilts/calyx/fdroid/repo/icons-240/org.sufficientlysecure.keychain.57500.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/org.sufficientlysecure.keychain.57500.png \
    prebuilts/calyx/fdroid/repo/icons-240/org.thoughtcrime.securesms.87700.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/org.thoughtcrime.securesms.87700.png \
    prebuilts/calyx/fdroid/repo/icons-240/org.torproject.torbrowser.2015808091.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/org.torproject.torbrowser.2015808091.png \
    prebuilts/calyx/fdroid/repo/icons-240/se.leap.riseupvpn.155.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-240/se.leap.riseupvpn.155.png \
    prebuilts/calyx/fdroid/repo/icons-320/app.organicmaps.21070806.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/app.organicmaps.21070806.png \
    prebuilts/calyx/fdroid/repo/icons-320/com.artifex.mupdf.viewer.app.90.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/com.artifex.mupdf.viewer.app.90.png \
    prebuilts/calyx/fdroid/repo/icons-320/com.aurora.store.38.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/com.aurora.store.38.png \
    prebuilts/calyx/fdroid/repo/icons-320/com.duckduckgo.mobile.android.58901.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/com.duckduckgo.mobile.android.58901.png \
    prebuilts/calyx/fdroid/repo/icons-320/com.jarsilio.android.scrambledeggsif.67.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/com.jarsilio.android.scrambledeggsif.67.png \
    prebuilts/calyx/fdroid/repo/icons-320/com.yubico.yubioath.20199.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/com.yubico.yubioath.20199.png \
    prebuilts/calyx/fdroid/repo/icons-320/info.guardianproject.locationprivacy.31.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/info.guardianproject.locationprivacy.31.png \
    prebuilts/calyx/fdroid/repo/icons-320/org.briarproject.briar.android.10305.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/org.briarproject.briar.android.10305.png \
    prebuilts/calyx/fdroid/repo/icons-320/org.calyxinstitute.vpn.149.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/org.calyxinstitute.vpn.149.png \
    prebuilts/calyx/fdroid/repo/icons-320/org.dmfs.tasks.82200.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/org.dmfs.tasks.82200.png \
    prebuilts/calyx/fdroid/repo/icons-320/org.secuso.privacyfriendlyweather.14.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/org.secuso.privacyfriendlyweather.14.png \
    prebuilts/calyx/fdroid/repo/icons-320/org.sufficientlysecure.keychain.57500.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/org.sufficientlysecure.keychain.57500.png \
    prebuilts/calyx/fdroid/repo/icons-320/org.thoughtcrime.securesms.87700.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/org.thoughtcrime.securesms.87700.png \
    prebuilts/calyx/fdroid/repo/icons-320/org.torproject.torbrowser.2015808091.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/org.torproject.torbrowser.2015808091.png \
    prebuilts/calyx/fdroid/repo/icons-320/se.leap.riseupvpn.155.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-320/se.leap.riseupvpn.155.png \
    prebuilts/calyx/fdroid/repo/icons-480/app.organicmaps.21070806.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/app.organicmaps.21070806.png \
    prebuilts/calyx/fdroid/repo/icons-480/com.artifex.mupdf.viewer.app.90.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/com.artifex.mupdf.viewer.app.90.png \
    prebuilts/calyx/fdroid/repo/icons-480/com.aurora.store.38.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/com.aurora.store.38.png \
    prebuilts/calyx/fdroid/repo/icons-480/com.duckduckgo.mobile.android.58901.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/com.duckduckgo.mobile.android.58901.png \
    prebuilts/calyx/fdroid/repo/icons-480/com.jarsilio.android.scrambledeggsif.67.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/com.jarsilio.android.scrambledeggsif.67.png \
    prebuilts/calyx/fdroid/repo/icons-480/com.yubico.yubioath.20199.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/com.yubico.yubioath.20199.png \
    prebuilts/calyx/fdroid/repo/icons-480/info.guardianproject.locationprivacy.31.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/info.guardianproject.locationprivacy.31.png \
    prebuilts/calyx/fdroid/repo/icons-480/org.briarproject.briar.android.10305.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/org.briarproject.briar.android.10305.png \
    prebuilts/calyx/fdroid/repo/icons-480/org.calyxinstitute.vpn.149.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/org.calyxinstitute.vpn.149.png \
    prebuilts/calyx/fdroid/repo/icons-480/org.dmfs.tasks.82200.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/org.dmfs.tasks.82200.png \
    prebuilts/calyx/fdroid/repo/icons-480/org.secuso.privacyfriendlyweather.14.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/org.secuso.privacyfriendlyweather.14.png \
    prebuilts/calyx/fdroid/repo/icons-480/org.sufficientlysecure.keychain.57500.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/org.sufficientlysecure.keychain.57500.png \
    prebuilts/calyx/fdroid/repo/icons-480/org.thoughtcrime.securesms.87700.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/org.thoughtcrime.securesms.87700.png \
    prebuilts/calyx/fdroid/repo/icons-480/org.torproject.torbrowser.2015808091.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/org.torproject.torbrowser.2015808091.png \
    prebuilts/calyx/fdroid/repo/icons-480/se.leap.riseupvpn.155.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-480/se.leap.riseupvpn.155.png \
    prebuilts/calyx/fdroid/repo/icons-640/app.organicmaps.21070806.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/app.organicmaps.21070806.png \
    prebuilts/calyx/fdroid/repo/icons-640/com.artifex.mupdf.viewer.app.90.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/com.artifex.mupdf.viewer.app.90.png \
    prebuilts/calyx/fdroid/repo/icons-640/com.aurora.store.38.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/com.aurora.store.38.png \
    prebuilts/calyx/fdroid/repo/icons-640/com.duckduckgo.mobile.android.58901.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/com.duckduckgo.mobile.android.58901.png \
    prebuilts/calyx/fdroid/repo/icons-640/com.jarsilio.android.scrambledeggsif.67.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/com.jarsilio.android.scrambledeggsif.67.png \
    prebuilts/calyx/fdroid/repo/icons-640/com.yubico.yubioath.20199.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/com.yubico.yubioath.20199.png \
    prebuilts/calyx/fdroid/repo/icons-640/info.guardianproject.locationprivacy.31.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/info.guardianproject.locationprivacy.31.png \
    prebuilts/calyx/fdroid/repo/icons-640/org.briarproject.briar.android.10305.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/org.briarproject.briar.android.10305.png \
    prebuilts/calyx/fdroid/repo/icons-640/org.calyxinstitute.vpn.149.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/org.calyxinstitute.vpn.149.png \
    prebuilts/calyx/fdroid/repo/icons-640/org.dmfs.tasks.82200.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/org.dmfs.tasks.82200.png \
    prebuilts/calyx/fdroid/repo/icons-640/org.secuso.privacyfriendlyweather.14.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/org.secuso.privacyfriendlyweather.14.png \
    prebuilts/calyx/fdroid/repo/icons-640/org.sufficientlysecure.keychain.57500.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/org.sufficientlysecure.keychain.57500.png \
    prebuilts/calyx/fdroid/repo/icons-640/org.thoughtcrime.securesms.87700.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/org.thoughtcrime.securesms.87700.png \
    prebuilts/calyx/fdroid/repo/icons-640/org.torproject.torbrowser.2015808091.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/org.torproject.torbrowser.2015808091.png \
    prebuilts/calyx/fdroid/repo/icons-640/se.leap.riseupvpn.155.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons-640/se.leap.riseupvpn.155.png \
    prebuilts/calyx/fdroid/repo/icons/app.organicmaps.21070806.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/app.organicmaps.21070806.png \
    prebuilts/calyx/fdroid/repo/icons/com.artifex.mupdf.viewer.app.90.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/com.artifex.mupdf.viewer.app.90.png \
    prebuilts/calyx/fdroid/repo/icons/com.aurora.store.38.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/com.aurora.store.38.png \
    prebuilts/calyx/fdroid/repo/icons/com.duckduckgo.mobile.android.58901.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/com.duckduckgo.mobile.android.58901.png \
    prebuilts/calyx/fdroid/repo/icons/com.jarsilio.android.scrambledeggsif.67.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/com.jarsilio.android.scrambledeggsif.67.png \
    prebuilts/calyx/fdroid/repo/icons/com.yubico.yubioath.20199.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/com.yubico.yubioath.20199.png \
    prebuilts/calyx/fdroid/repo/icons/fdroid-icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/fdroid-icon.png \
    prebuilts/calyx/fdroid/repo/icons/info.guardianproject.locationprivacy.31.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/info.guardianproject.locationprivacy.31.png \
    prebuilts/calyx/fdroid/repo/icons/org.briarproject.briar.android.10305.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/org.briarproject.briar.android.10305.png \
    prebuilts/calyx/fdroid/repo/icons/org.calyxinstitute.vpn.149.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/org.calyxinstitute.vpn.149.png \
    prebuilts/calyx/fdroid/repo/icons/org.dmfs.tasks.82200.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/org.dmfs.tasks.82200.png \
    prebuilts/calyx/fdroid/repo/icons/org.secuso.privacyfriendlyweather.14.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/org.secuso.privacyfriendlyweather.14.png \
    prebuilts/calyx/fdroid/repo/icons/org.sufficientlysecure.keychain.57500.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/org.sufficientlysecure.keychain.57500.png \
    prebuilts/calyx/fdroid/repo/icons/org.thoughtcrime.securesms.87700.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/org.thoughtcrime.securesms.87700.png \
    prebuilts/calyx/fdroid/repo/icons/org.torproject.torbrowser.2015808091.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/org.torproject.torbrowser.2015808091.png \
    prebuilts/calyx/fdroid/repo/icons/se.leap.riseupvpn.155.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/icons/se.leap.riseupvpn.155.png \
    prebuilts/calyx/fdroid/repo/index.jar:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.jar \
    prebuilts/calyx/fdroid/repo/index-v1.jar:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index-v1.jar \
    prebuilts/calyx/fdroid/repo/index-v1.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index-v1.json \
    prebuilts/calyx/fdroid/repo/index.xml:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/index.xml \
    prebuilts/calyx/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon_UfcETKkTEGd872Z6zctH-WOVkse-62g4ltY6-a4l05M=.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.openobservatory.ooniprobe/en-US/icon_UfcETKkTEGd872Z6zctH-WOVkse-62g4ltY6-a4l05M=.png \
    prebuilts/calyx/fdroid/repo/org.torproject.android/en-US/icon.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.torproject.android/en-US/icon.png \
    prebuilts/calyx/fdroid/repo/org.torproject.android/en-US/icon_-ruI6LRx167zWkMlD5D-H8Je_pfB2i79g4KurXbHAmY=.png:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/org.torproject.android/en-US/icon_-ruI6LRx167zWkMlD5D-H8Je_pfB2i79g4KurXbHAmY=.png \
    prebuilts/calyx/fdroid/repo/status/running.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/status/running.json \
    prebuilts/calyx/fdroid/repo/status/update.json:$(TARGET_COPY_OUT_PRODUCT)/fdroid/repo/status/update.json \

PRODUCT_PACKAGES += \
    fdroid-repo \
    AuroraStore \
    Briar \
    CalyxVPN \
    DAVx5 \
    DuckDuckGoPrivacyBrowser \
    K-9Mail \
    LocationPrivacy \
    MuPDFviewer \
    Nextcloud \
    OONIProbe \
    OpenKeychain \
    Orbot \
    OrganicMaps \
    RiseupVPN \
    ScrambledExif \
    Signal \
    Tasks \
    TorBrowser \
    Weather \
    YubicoAuthenticator \
